apiVersion: v1
kind: ConfigMap
metadata:
  name: otus-sw-arch-order-config
data:
  APP_NAME: {{ .Release.Name }}
  BILLING_SERVICE_URL: {{ .Values.config.billing_service_url }}
  NOTIFICATION_SERVICE_URL: {{ .Values.config.notification_service_url }}
---
apiVersion: v1
kind: Secret
metadata:
  name: otus-sw-arch-order-secret
type: Opaque
data:
  DATABASE_URI: {{ printf "postgresql+psycopg2://%s:%s@%s:%s/%s" .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword (include "postgresql.fullname" .) .Values.postgresql.service.port .Values.postgresql.postgresqlDatabase  | b64enc | quote }}
  DATABASE_URI_JOB: {{ printf "postgresql://%s:%s@%s:%s/%s" .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword (include "postgresql.fullname" .) .Values.postgresql.service.port .Values.postgresql.postgresqlDatabase  | b64enc | quote }}